[build]
  command = "cd ../.. && pnpm install --no-frozen-lockfile && cd apps/web && npx prisma generate --schema=./prisma/schema.prisma && npx prisma db push --schema=./prisma/schema.prisma --accept-data-loss && pnpm run build"
  publish = ".next"
  base = "apps/web"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
